import {describe,expect,it,vi} from 'vitest';
import {loadComposeEmail} from '../apps/mail/src/ui/load-compose';
import type {MailClient} from '../apps/mail/src/ui/jmap';
describe('Compose source hydration',()=>{
 it('requests full bodies before editing a metadata-only persisted draft',async()=>{const source={id:'draft',keywords:{$draft:true},from:null,to:null,cc:null,bcc:null,textBody:[{partId:'text',type:'text/plain'}],htmlBody:[],bodyValues:{text:{value:'This draft should survive a reload.'}}};const call=vi.fn(async()=>({list:[source]}));const result=await loadComposeEmail({call} as unknown as MailClient,'account','draft',true);expect(call).toHaveBeenCalledWith('Email/get',{ids:['draft'],fetchAllBodyValues:true,maxBodyValueBytes:0},'account');expect(result.bodyValues?.text.value).toBe('This draft should survive a reload.');});
 it('requests full immutable source for replies as well',async()=>{const call=vi.fn(async()=>({list:[{id:'original',keywords:{},textBody:[{partId:'p'}],htmlBody:[],bodyValues:{p:{value:'Original quoted text'}}}]}));expect((await loadComposeEmail({call} as unknown as MailClient,'account','original')).bodyValues?.p.value).toBe('Original quoted text');});
 it.each([{bodyValues:{}},{bodyValues:{p:{value:'partial',isTruncated:true}}}])('refuses missing or truncated source rather than allowing a blank overwrite',async({bodyValues})=>{const call=vi.fn(async()=>({list:[{id:'draft',keywords:{$draft:true},textBody:[{partId:'p'}],htmlBody:[],bodyValues}]}));await expect(loadComposeEmail({call} as unknown as MailClient,'a','draft',true)).rejects.toThrow('complete message body');});
 it('refuses a message that was submitted or removed from drafts',async()=>{const call=vi.fn(async()=>({list:[{id:'draft',keywords:{},textBody:[],htmlBody:[]}]}));await expect(loadComposeEmail({call} as unknown as MailClient,'a','draft',true)).rejects.toThrow('no longer a draft');});
 it('carries CID images from body lists without treating binary image bytes as message text',async()=>{const image={partId:'image',blobId:'authorized-image',type:'image/png',cid:'logo',disposition:'inline',size:20};const call=vi.fn(async()=>({list:[{id:'source',keywords:{},attachments:[],textBody:[{partId:'plain',type:'text/plain'},image],htmlBody:[{partId:'rich',type:'text/html'},image],bodyValues:{plain:{value:'Plain'},rich:{value:'<p>Rich<img src="cid:logo"></p>'}}}]}));const source=await loadComposeEmail({call} as unknown as MailClient,'a','source');expect(source.textBody).toEqual([{partId:'plain',type:'text/plain'}]);expect(source.htmlBody).toEqual([{partId:'rich',type:'text/html'}]);expect(source.attachments).toEqual([image]);});
 it('keeps plain-only messages in plain text when JMAP provides a plain fallback in htmlBody',async()=>{const plain={partId:'plain',type:'text/plain'};const call=vi.fn(async()=>({list:[{id:'source',keywords:{},attachments:[],textBody:[plain],htmlBody:[plain],bodyValues:{plain:{value:'Literal <characters>'}}}]}));const source=await loadComposeEmail({call} as unknown as MailClient,'a','source');expect(source.htmlBody).toEqual([]);expect(source.textBody).toEqual([plain]);});
});
