import { afterEach, describe, expect, it, vi } from 'vitest';
import { DatabaseSync } from 'node:sqlite';
import { MailAccount, type MailAccountEnvironment } from '../apps/mail/src/server/account';
const databases:DatabaseSync[]=[];
afterEach(()=>{vi.unstubAllGlobals();for(const database of databases.splice(0))database.close();});

/** Real product SQL/R2 seams; only external Core/credential/provider authority is mocked. */
async function dispatchFixture(){
  const database=new DatabaseSync(':memory:');databases.push(database);let nesting=0,failAttempt=false;let duringCore:(()=>void|Promise<void>)|undefined,duringMime:(()=>void|Promise<void>)|undefined;
  const storage={sql:{exec<T>(query:string,...bindings:unknown[]):Iterable<T>{if(failAttempt&&query.startsWith('INSERT INTO mail_objects')&&bindings[0]==='EmailSubmission'&&JSON.parse(String(bindings[2])).status==='sending')throw new Error('Injected attempt commit failure');const statement=database.prepare(query);return (statement.columns().length?statement.all(...bindings as any[]):[statement.run(...bindings as any[])]) as T[];}},transactionSync<T>(task:()=>T):T{const save=`dispatch_${++nesting}`;database.exec(`SAVEPOINT ${save}`);try{const result=task();database.exec(`RELEASE ${save}`);return result;}catch(error){database.exec(`ROLLBACK TO ${save}; RELEASE ${save}`);throw error;}},async setAlarm(_time:number){},async deleteAlarm(){}};
  const blobs=new Map<string,Uint8Array>();const credentialId=crypto.randomUUID(),jobId=crypto.randomUUID(),expiresAt=Date.now()+90*86400000;const actions=['mail.read','mail.draft','mail.organize','mail.manage','mail.send'];
  const credential={id:credentialId,jobId,version:1,revokedAt:null as number|null,expiresAt,accountId:'account',organizationId:'org',workspaceId:'workspace',actorId:'actor',lifecycleGeneration:0,actions};
  const env:MailAccountEnvironment={CF_ACCOUNT_ID:'fixture-account',CF_API_TOKEN:'local-token',MAIL_BLOBS:{async put(key,value){blobs.set(key,value instanceof ReadableStream?new Uint8Array(await new Response(value).arrayBuffer()):new Uint8Array(value));},async get(key,options){const value=blobs.get(key);if(!value)return null;const bytes=options?.range?value.slice(options.range.offset,options.range.offset+options.range.length):value;return {size:value.length,body:new Response(bytes.slice()).body!,async arrayBuffer(){await duringMime?.();return bytes.slice().buffer;}};},async delete(key){blobs.delete(key);}},MAIL_DIRECTORY:{idFromName:()=>0,get:()=>({async fetch(){return Response.json({allowed:true});}})},MAIL_CREDENTIALS:{idFromName:()=>0,get:()=>({async fetch(){return Response.json({credential:{...credential}});}})},CORE:{async fetch(request){const body=await request.json() as any;await duringCore?.();return Response.json({authorization:{allowed:true,effectiveActions:body.actions},resource:{id:'account'},context:{organizationId:'org',workspaceId:'workspace',actorId:'actor'},jobId});}}};
  const context={accountId:'account',organizationId:'org',workspaceId:'workspace',actor:{id:'actor',actions},authorityProof:{lease:'opaque-dispatch-proof',jobId,expiresAt,actions,credentialId,credentialVersion:1}};let account=new MailAccount({storage},env);
  const call=async(name:string,args:any={})=>{const response=await account.fetch(new Request('https://account/jmap',{method:'POST',body:JSON.stringify({...context,request:{using:['urn:ietf:params:jmap:core','urn:ietf:params:jmap:mail'],methodCalls:[[name,{accountId:'account',...args},'call']]}})}));return (await response.json() as any).methodResponses[0][1];};
  await call('Email/get',{ids:[]});database.prepare('INSERT INTO mail_objects(type,id,json) VALUES(?,?,?)').run('Domain','domain',JSON.stringify({id:'domain',name:'example.com',zoneId:'zone',sendingVerified:true}));database.prepare('INSERT INTO mail_objects(type,id,json) VALUES(?,?,?)').run('Identity','identity',JSON.stringify({id:'identity',email:'sender@example.com',verified:true}));account=new MailAccount({storage},env);
  const draft=(await call('Email/set',{create:{draft:{from:[{email:'sender@example.com'}],to:[{email:'recipient@example.net'}],subject:'Dispatch fence',textBody:[{partId:'text',type:'text/plain'}],bodyValues:{text:{value:'Prepared known body'}},mailboxIds:{'folder-drafts':true},keywords:{'$draft':true}}}})).created.draft;
  const accepted=await call('EmailSubmission/set',{create:{send:{emailId:draft.id,identityId:'identity'}}});expect(accepted.notCreated).toEqual({});const id=accepted.created.send.id;const initial=JSON.parse(String(database.prepare("SELECT json FROM mail_objects WHERE type='EmailSubmission' AND id=?").get(id)?.json));initial.sendAt=new Date(Date.now()-1000).toISOString();database.prepare("UPDATE mail_objects SET json=? WHERE type='EmailSubmission' AND id=?").run(JSON.stringify(initial),id);account=new MailAccount({storage},env);
  let attempts=0;vi.stubGlobal('fetch',async()=>{attempts++;return Response.json({success:true,result:{message_id:'provider-one',queued:['recipient@example.net']}});});
  return {credential,alarm:()=>account.alarm(),restart(){account=new MailAccount({storage},env);},duringCore(hook:()=>void|Promise<void>){duringCore=hook;},duringMime(hook:()=>void|Promise<void>){duringMime=hook;},failAttempt(){failAttempt=true;},attempts:()=>attempts,submission:()=>JSON.parse(String(database.prepare("SELECT json FROM mail_objects WHERE type='EmailSubmission' AND id=?").get(id)?.json))};
}

describe('Final outbound authorization fence',()=>{
  it('rejects credential revocation during Core verification with zero provider attempts',async()=>{const f=await dispatchFixture();f.duringCore(async()=>{await Promise.resolve();f.credential.revokedAt=Date.now();});await f.alarm();expect(f.attempts()).toBe(0);expect(f.submission().status).toBe('failed');expect(f.submission().attemptedAt).toBeUndefined();f.credential.revokedAt=null;await f.alarm();expect(f.attempts()).toBe(0);});
  it('durably rejects credential revocation during R2 MIME preparation before attempt',async()=>{const f=await dispatchFixture();f.duringMime(async()=>{await Promise.resolve();f.credential.revokedAt=Date.now();});await f.alarm();expect(f.attempts()).toBe(0);expect(f.submission().status).toBe('failed');expect(f.submission().error).toBe('authorizationRevokedBeforeAttempt');expect(f.submission().attemptedAt).toBeUndefined();f.credential.revokedAt=null;f.restart();await f.alarm();expect(f.attempts()).toBe(0);});
  it('keeps a failed durable attempt commit pending and never classifies it as uncertain',async()=>{const f=await dispatchFixture();f.failAttempt();await expect(f.alarm()).rejects.toThrow('Injected attempt commit failure');expect(f.attempts()).toBe(0);expect(f.submission().status).toBe('pending');expect(f.submission().attemptedAt).toBeUndefined();f.restart();expect(f.submission().status).toBe('pending');expect(f.submission().status).not.toBe('uncertain');});
});
