import { afterEach, describe, expect, it } from 'vitest';
import { DatabaseSync } from 'node:sqlite';
import { SqliteMailMigration, migrationSourceUrl, type MigrationCallbacks } from '../apps/mail/src/server/migration';
import type { MailSqlStorage } from '../apps/mail/src/server/store';
const databases:DatabaseSync[]=[];
afterEach(()=>{databases.splice(0).forEach(db=>db.close());});
function fixture(count=27){
  const db=new DatabaseSync(':memory:');databases.push(db);
  const storage:MailSqlStorage={sql:{exec<T>(sql:string,...args:unknown[]):Iterable<T>{const statement=db.prepare(sql);return (statement.columns().length?statement.all(...args as any[]):[statement.run(...args as any[])]) as T[];}},transactionSync<T>(fn:()=>T){db.exec('SAVEPOINT migration');try{const result=fn();db.exec('RELEASE migration');return result;}catch(error){db.exec('ROLLBACK TO migration; RELEASE migration');throw error;}}};
  const imported:{raw:string;metadata:any}[]=[],boxes:any[]=[],calls:{url:string;request:RequestInit}[]=[];let failDownload:string|undefined;let queryState='q1';let redirect=false;let oversize=false;
  const fetcher:typeof fetch=async(url:any,request:any)=>{calls.push({url:String(url),request});if(redirect)return new Response(null,{status:302,headers:{Location:'https://attacker.net'}});const target=new URL(String(url));
    if(target.pathname==='/session')return Response.json({capabilities:{'urn:ietf:params:jmap:mail':{}},primaryAccounts:{'urn:ietf:params:jmap:mail':'source'},accounts:{source:{accountCapabilities:{'urn:ietf:params:jmap:mail':{}}}},apiUrl:'https://mail.provider.com/api',downloadUrl:'https://mail.provider.com/download/{accountId}/{blobId}/{name}?type={type}'});
    if(target.pathname==='/api'){const [method,args,tag]=JSON.parse(request.body).methodCalls[0];let result:any;if(method==='Mailbox/get')result={list:[{id:'child',name:'Project',parentId:'parent'},{id:'parent',name:'Work',parentId:null},{id:'inbox',name:'Inbox',role:'inbox'}]};if(method==='Email/query')result={ids:Array.from({length:Math.min(args.limit,count-args.position)},(_,i)=>'email'+(i+args.position)),total:count,position:args.position,queryState};if(method==='Email/get')result={list:args.ids.map((id:string)=>({id,blobId:id,mailboxIds:{child:true,inbox:true},keywords:{$seen:true},receivedAt:'2026-10-05T00:00:00Z'}))};return Response.json({methodResponses:[[method,result,tag]]});}
    const id=target.pathname.split('/')[3];if(failDownload===id)throw new Error('Download fixture failure');if(oversize)return new Response('too big',{headers:{'content-length':String(25*1024*1024+1)}});return new Response('Subject: '+id+'\r\n\r\nHello');};
  const callbacks:MigrationCallbacks={async createMailbox(box,parentId,operationId){boxes.push({box,parentId,operationId});return 'mapped-'+box.id;},async importRaw(raw,metadata){const existing=imported.find(item=>item.metadata.operationId===metadata.operationId);if(!existing)imported.push({raw:new TextDecoder().decode(raw),metadata});return {id:'dest-'+metadata.sourceEmailId,isDuplicate:!!existing};}};
  const env={MAIL_MIGRATION_KEY:'fixture-key-kept-on-server-32-chars-minimum',MAIL_MIGRATION_ALLOWED_ORIGINS:'https://mail.provider.com'};
  return {db,storage,callbacks,env,fetcher,imported,boxes,calls,store:new SqliteMailMigration(storage,env,callbacks,fetcher),failDownload(id?:string){failDownload=id;},changeState(){queryState='q2';},redirect(){redirect=true;},oversize(){oversize=true;}};
}
const input={sessionUrl:'https://mail.provider.com/session',credential:'source-private-secret',operationId:'12345678-1234-4234-8234-123456789012'};
describe('server JMAP account migration',()=>{
  it('invokes source fetch without rebinding its native receiver',async()=>{const f=fixture(1);const nativeLike:typeof fetch=async function(this:unknown,url,request){expect(this).toBeUndefined();return f.fetcher(url,request);};const store=new SqliteMailMigration(f.storage,f.env,f.callbacks,nativeLike);const job=await store.start(input,'actor');expect(await store.step(job.id,'actor')).toMatchObject({state:'completed',imported:1});expect(f.calls.length).toBeGreaterThan(0);});
  it('encrypts source credentials, keeps public metadata clean and binds access to the actor',async()=>{const f=fixture();const job=await f.store.start(input,'actor');expect(JSON.stringify(job)).not.toContain(input.credential);expect(String(f.db.prepare('SELECT data FROM mail_migration_jobs').get()?.data)).not.toContain(input.credential);expect(f.store.list('different')).toEqual([]);expect(()=>f.store.get(job.id,'different')).toThrow('not found');expect(await f.store.start(input,'actor')).toEqual(job);await expect(f.store.start({...input,credential:'different'},'actor')).rejects.toThrow('conflict');});
  it('imports bounded pages and resumes from persisted checkpoints preserving hierarchy and metadata',async()=>{const f=fixture();const job=await f.store.start(input,'actor');const first=await f.store.step(job.id,'actor');expect(first).toMatchObject({state:'running',phase:'emails',cursor:25,imported:25,total:27});expect(f.boxes.map(value=>value.box.id)).toEqual(['parent','inbox','child']);expect(f.boxes[2].parentId).toBe('mapped-parent');expect(f.imported[0].metadata).toMatchObject({mailboxIds:{'mapped-child':true,'mapped-inbox':true},keywords:{$seen:true},receivedAt:'2026-10-05T00:00:00Z'});const restarted=new SqliteMailMigration(f.storage,f.env,f.callbacks,f.fetcher);expect(await restarted.step(job.id,'actor')).toMatchObject({state:'completed',cursor:27,imported:27});expect(JSON.parse(String(f.db.prepare('SELECT data FROM mail_migration_jobs').get()?.data)).secret).toBeUndefined();expect(f.calls.every(call=>call.request.redirect==='manual'&&new URL(call.url).origin==='https://mail.provider.com')).toBe(true);});
  it('uses receipts to skip successful imports after a failure inside a page',async()=>{const f=fixture(5);f.failDownload('email2');const job=await f.store.start(input,'actor');expect(await f.store.step(job.id,'actor')).toMatchObject({state:'failed',cursor:0,imported:2});f.failDownload();expect(await new SqliteMailMigration(f.storage,f.env,f.callbacks,f.fetcher).step(job.id,'actor')).toMatchObject({state:'completed',cursor:5,imported:5});expect(f.imported).toHaveLength(5);});
  it('clears credentials on cancellation and performs no further source requests',async()=>{const f=fixture();const job=await f.store.start(input,'actor');f.store.cancel(job.id,'actor');expect(await f.store.step(job.id,'actor')).toMatchObject({state:'cancelled'});expect(f.calls).toHaveLength(0);expect(JSON.parse(String(f.db.prepare('SELECT data FROM mail_migration_jobs').get()?.data)).secret).toBeUndefined();});
  it('fails honestly with no configured encryption secret',async()=>{const f=fixture();await expect(new SqliteMailMigration(f.storage,{},f.callbacks,f.fetcher).start(input,'actor')).rejects.toThrow('MAIL_MIGRATION_KEY');});
  it('requires explicitly trusted source origins and rechecks approval when resumed',async()=>{const f=fixture();await expect(new SqliteMailMigration(f.storage,{MAIL_MIGRATION_KEY:f.env.MAIL_MIGRATION_KEY},f.callbacks,f.fetcher).start(input,'actor')).rejects.toThrow('trusted source origins');await expect(f.store.start({...input,sessionUrl:'https://untrusted.provider.com/session'},'actor')).rejects.toThrow('not approved');const job=await f.store.start(input,'actor');f.env.MAIL_MIGRATION_ALLOWED_ORIGINS='https://different.provider.com';expect(await f.store.step(job.id,'actor')).toMatchObject({state:'failed',error:expect.stringContaining('not approved')});expect(f.calls).toHaveLength(0);});
  it.each(['http://mail.provider.com','https://localhost','https://127.0.0.1','https://10.0.0.1','https://2130706433','https://[::1]','https://host.local','https://host.internal','https://user:pass@mail.provider.com','https://mail.provider.com:8443'])('rejects unsafe source %s',url=>{expect(()=>migrationSourceUrl(url)).toThrow();});
  it('rejects discovery URLs outside the source origin and redirects',async()=>{expect(()=>migrationSourceUrl('https://other.provider.com/api','https://mail.provider.com')).toThrow();const f=fixture();f.redirect();const job=await f.store.start(input,'actor');expect(await f.store.step(job.id,'actor')).toMatchObject({state:'failed'});expect(f.imported).toHaveLength(0);});
  it('bounds raw downloads and refuses shifting source query snapshots',async()=>{const f=fixture();const job=await f.store.start(input,'actor');await f.store.step(job.id,'actor');f.changeState();expect(await f.store.step(job.id,'actor')).toMatchObject({state:'failed',cursor:25});const big=fixture(1);big.oversize();const other=await big.store.start(input,'actor');expect(await big.store.step(other.id,'actor')).toMatchObject({state:'failed',imported:0,error:expect.stringContaining('size limit')});});
});
