import React,{useEffect,useState} from 'react';
import {Button} from '@open-cloud/ui';
import type {MailClient} from './jmap';
interface PushInfo {list:{id:string;deviceClientId:string;verificationCode:string|null;expires:string}[];applicationServerKey:string;deliveryStates:Record<string,string>}
const supported=()=>typeof Notification!=='undefined'&&'serviceWorker' in navigator&&'PushManager' in window;
function deviceKey(client:MailClient){const s=client.session;return 'enough-mail-notifications:'+JSON.stringify([s.organizationId,s.workspaceId,s.actorId]);}
async function configure(registration:ServiceWorkerRegistration,config:unknown){const worker=registration.active;if(!worker)throw new Error('The notification service is still starting. Try again.');await new Promise<void>((resolve,reject)=>{const channel=new MessageChannel(),timer=setTimeout(()=>reject(new Error('Notification setup timed out.')),5000);channel.port1.onmessage=event=>{clearTimeout(timer);channel.port1.close();event.data?.saved?resolve():reject(new Error('Device storage is unavailable.'));};worker.postMessage({type:'MAIL_NOTIFICATIONS_CONFIG',config},[channel.port2]);});}
/** Prompt on opening/focusing Mail, before a device subscription expires. */
export function NotificationRenewalPrompt({client,onRenew}:{client:MailClient;onRenew:()=>void}){
 const [expires,setExpires]=useState<number|null>(null);
 useEffect(()=>{if(!supported())return;let active=true;
  const check=()=>{const value=Number(localStorage.getItem(deviceKey(client)+':expires'));if(active)setExpires(value>0?value:null);};
  check();void(async()=>{const device=localStorage.getItem(deviceKey(client));if(!device)return;const browser=await(await navigator.serviceWorker.getRegistration('/apps/mail/'))?.pushManager.getSubscription();if(!browser){localStorage.setItem(deviceKey(client)+':expires','1');check();return;}const info=await client.call<PushInfo>('PushSubscription/get',{});const row=info.list.find(row=>row.deviceClientId===device);localStorage.setItem(deviceKey(client)+':expires',String(row?Date.parse(row.expires):1));check();})().catch(()=>{});
  window.addEventListener('focus',check);window.addEventListener('mail-notification-preference',check);const timer=window.setInterval(check,3600000);
  return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',check);window.removeEventListener('mail-notification-preference',check);};
 },[client]);
 if(!expires||expires-Date.now()>7*86400000)return null;
 return <div className="mail-alert" role="status"><span>{expires<=Date.now()?'Background mail notifications have expired. Renew them to receive new-mail alerts.':'Background mail notifications expire soon. Renew them to keep receiving new-mail alerts.'}</span><Button size="sm" variant="outline" onClick={onRenew}>Renew notifications</Button></div>;
}
export default function BrowserNotifications({client}:{client:MailClient}){
 const [subscribed,setSubscribed]=useState(false);const [lastNotification,setLastNotification]=useState<number|null>(null);
 const [enabled,setEnabled]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const [permission,setPermission]=useState(supported()?Notification.permission:'unsupported');
 useEffect(()=>{if(!supported())return;let active=true;const listener=(event:MessageEvent)=>{if(event.data?.type==='MAIL_PUSH_VERIFIED'&&active){setEnabled(event.data.verified===true);setMessage(event.data.verified?'Notifications are enabled on this device.':'Open this page and try enabling notifications again.');}};navigator.serviceWorker.addEventListener('message',listener);void (async()=>{const registration=await navigator.serviceWorker.getRegistration('/apps/mail/');if(registration?.active){const channel=new MessageChannel();channel.port1.onmessage=event=>{if(active&&Number.isFinite(event.data?.lastNotificationAt))setLastNotification(event.data.lastNotificationAt);channel.port1.close();};registration.active.postMessage({type:'MAIL_NOTIFICATIONS_STATUS'},[channel.port2]);}const browser=await registration?.pushManager.getSubscription();if(!browser)return;const info=await client.call<PushInfo>('PushSubscription/get',{});const stored=localStorage.getItem(deviceKey(client));const row=info.list.find(row=>row.deviceClientId===stored);if(active){setSubscribed(!!row);setEnabled(!!row?.verificationCode&&Date.parse(row.expires)>Date.now());}})().catch(()=>{});return()=>{active=false;navigator.serviceWorker.removeEventListener('message',listener);};},[client]);
 async function run(action:()=>Promise<void>){setBusy(true);setError('');try{await action();}catch(cause){setError(cause instanceof Error?cause.message:'Notification setup failed.');}finally{setBusy(false);}}
 async function enable(){const granted=await Notification.requestPermission();setPermission(granted);if(granted!=='granted')throw new Error(granted==='denied'?'Notifications are blocked. Allow them in this site’s browser settings, then try again.':'Notification permission was not granted.');
  const info=await client.call<PushInfo>('PushSubscription/get',{});if(!info.applicationServerKey)throw new Error('Background notifications are not configured on this server.');
  await navigator.serviceWorker.register('/apps/mail/mail-sw.js',{scope:'/apps/mail/'});const registration=await navigator.serviceWorker.ready;
  const key=deviceKey(client);let device=localStorage.getItem(key);if(!device){device=crypto.randomUUID();localStorage.setItem(key,device);}
  const existing=info.list.filter(row=>row.deviceClientId===device);if(existing.length)await client.call('PushSubscription/set',{destroy:existing.map(row=>row.id)});
  const old=await registration.pushManager.getSubscription();if(old)await old.unsubscribe();
  const bytes=Uint8Array.from(atob(info.applicationServerKey.replaceAll('-','+').replaceAll('_','/')),char=>char.charCodeAt(0));
  const subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes});const value=subscription.toJSON();
  await configure(registration,{enabled:true,apiUrl:client.session.apiUrl,states:info.deliveryStates});
  setMessage('Waiting for the browser’s push verification. A setup notification will confirm when it is ready.');
  try{const created=await client.call<{created:{browser:{expires:string}}}>('PushSubscription/set',{create:{browser:{deviceClientId:device,url:value.endpoint,keys:value.keys,types:['EmailDelivery'],expires:new Date(Date.now()+29*86400000).toISOString()}}});localStorage.setItem(deviceKey(client)+':expires',String(Date.parse(created.created.browser.expires)));window.dispatchEvent(new Event('mail-notification-preference'));setSubscribed(true);}catch(cause){await configure(registration,{enabled:false});await subscription.unsubscribe();throw cause;}
 }
 async function disable(){const registration=await navigator.serviceWorker.getRegistration('/apps/mail/');if(registration)await configure(registration,{enabled:false});const device=localStorage.getItem(deviceKey(client));const info=await client.call<PushInfo>('PushSubscription/get',{});const owned=info.list.filter(row=>row.deviceClientId===device);if(owned.length)await client.call('PushSubscription/set',{destroy:owned.map(row=>row.id)});await (await registration?.pushManager.getSubscription())?.unsubscribe();localStorage.removeItem(deviceKey(client));localStorage.removeItem(deviceKey(client)+':expires');window.dispatchEvent(new Event('mail-notification-preference'));setEnabled(false);setSubscribed(false);setMessage('Notifications are off on this device.');}
 return <section><p>Get a system notification for new inbox mail, even when this tab is closed. Sender names and message contents stay private.</p><p>Notifications apply to this browser and all inboxes you can read. They last up to 29 days; return here to renew them. Your browser and device must allow background notifications.</p><p role="status">{permission==='unsupported'?'This browser does not support background notifications.':enabled?'Enabled on this device.':permission==='denied'?'Blocked in your browser’s site settings.':'Not enabled on this device.'} {message}</p>{lastNotification&&<p>Last new mail notification: {new Date(lastNotification).toLocaleString()}</p>}{error&&<p role="alert">{error}</p>}<div className="mail-compose-notice-actions"><Button disabled={busy||permission==='unsupported'} onClick={()=>void run(enable)}>{enabled?'Renew notifications':'Enable notifications'}</Button><Button variant="outline" disabled={busy||!subscribed} onClick={()=>void run(disable)}>Turn off</Button><Button variant="outline" disabled={busy||!enabled} onClick={()=>void run(async()=>{const registration=await navigator.serviceWorker.ready;await registration.showNotification('Enough Mail',{body:'Your browser notifications are working.',icon:'/apps/mail/icons/mail-192.png',tag:'enough-mail-test'});})}>Send test notification</Button></div></section>;
}
