import React from 'react';
import {createRoot} from 'react-dom/client';
import '../apps/mail/src/styles.css';
import Settings from '../apps/mail/src/ui/Settings';
import Compose from '../apps/mail/src/ui/Compose';
import Outbox from '../apps/mail/src/ui/Outbox';
import OfflineQueue from '../apps/mail/src/ui/OfflineQueue';
import MailApp from '../apps/mail/src/ui/MailApp';
import {MailClient,MAIL_CAP,SUBMISSION_CAP,draftCacheKey} from '../apps/mail/src/ui/jmap';
import {cacheScope} from '../apps/mail/src/ui/offline';

if(!['localhost','127.0.0.1'].includes(location.hostname))throw new Error('Local fixture only');
// Review fixtures contain only reserved .test addresses.
const params=new URLSearchParams(location.search), screen=params.get('screen')||'Inbox', state=params.get('state')||'populated';
const accountId=params.get('account')||'review-inbox',actions=state==='readonly'?['mail.read']:['mail.read','mail.organize','mail.draft','mail.send','mail.manage'];
const allAccounts:any={'review-inbox':{name:'Personal',isReadOnly:state==='readonly',accountCapabilities:{[MAIL_CAP]:{},[SUBMISSION_CAP]:{},'urn:enough:params:jmap:mail':{actions}}},'review-work':{name:'Studio',isReadOnly:state==='readonly',accountCapabilities:{[MAIL_CAP]:{},[SUBMISSION_CAP]:{},'urn:enough:params:jmap:mail':{actions}}}};
const session:any={username:'alex@example.test',actorId:'review-alex',organizationId:'review-org',workspaceId:'review-workspace',apiUrl:'/apps/mail/jmap',uploadUrl:'/fixture-upload',downloadUrl:'/fixture-download/{accountId}/{blobId}/{name}',capabilities:{[MAIL_CAP]:{},[SUBMISSION_CAP]:{}},accounts:state==='onboarding'?{}:allAccounts,primaryAccounts:{[MAIL_CAP]:accountId}};
const mailboxes=['inbox','drafts','sent','archive','junk','trash'].map(role=>({id:`folder-${role}`,name:role==='junk'?'Spam':role[0].toUpperCase()+role.slice(1),role,parentId:null,totalEmails:12,unreadEmails:role==='inbox'?3:0})).concat([{id:'projects',name:'Projects',role:null,parentId:null,totalEmails:4,unreadEmails:1}] as any);
const identities=[{id:'identity-alex',name:'Alex Morgan',email:'alex@example.test',verified:true,textSignature:'Alex Morgan\nProduct design · Morgan Studio\nhttps://studio.example.test',htmlSignature:'<p><strong>Alex Morgan</strong><br>Product design · Morgan Studio</p>'}];
const body='Hi Alex,\n\nHere is the updated project plan. The design review is on Thursday at 10am. Could you look over the milestones before then?\n\nThanks,\nJamie';
const messages:any[]=[['Design review on Thursday','Jamie Chen','jamie@example.test'],['Your booking is confirmed','Coast House','bookings@example.test'],['Re: Autumn launch plan','Taylor Reed','taylor@example.test'],['Weekly team notes','Sam Rivera','sam@example.test'],['Invoice for September','Studio North','accounts@example.test'],['A few ideas for the weekend','Robin Lee','robin@example.test']].map(([subject,name,email],i)=>({id:`message-${i}`,threadId:`thread-${i}`,blobId:`blob-${i}`,subject,from:[{name,email}],to:[{name:'Alex Morgan',email:'alex@example.test'}],cc:i===0?[{name:'Taylor Reed',email:'taylor@example.test'}]:[],mailboxIds:{'folder-inbox':true},keywords:i>2?{$seen:true}:i===1?{$flagged:true}:{},receivedAt:new Date(Date.now()-i*86400000).toISOString(),preview:body.replaceAll('\n',' '),hasAttachment:i===0,textBody:[{partId:'text',blobId:'body',type:'text/plain',size:body.length}],bodyValues:{text:{value:body}},attachments:i===0?[{blobId:'attachment',name:'Project plan.pdf',type:'application/pdf',size:204800}]:[],headers:[{name:'Message-ID',value:`<${i}@example.test>`}]}));
messages[0].mailboxIds.projects=true;
messages[0].keywords.$important=true;
messages[2].from=[{email:'a-very-long-sender-address-for-wrapping@example.test'}];
messages[2].cc=[{name:'Robin Lee',email:'robin@example.test'},{name:'Sam Rivera',email:'sam@example.test'}];
const newsletterHtml=`<div style="max-width:680px;margin:auto;background:#fff;padding:28px"><img src="cid:studio-logo" alt="Studio North newsletter logo" width="96" height="32"><h1>Good things take shape</h1><p style="color:#667085">The Studio North monthly letter — October</p><img src="https://127.0.0.1:5197/fixture-newsletter-cover.jpg" width="620" height="210" alt="Autumn collection cover image"><p>Welcome to our monthly collection of thoughtful work, practical ideas and things we have been making.</p>${Array.from({length:8},(_,i)=>`<h2>${['A fresh perspective','From the workshop','Small details, big difference','What we are reading'][i%4]}</h2><p>Design should make everyday life easier. This month we explored materials, refined our prototypes and worked with our community to make more useful things. Here are the ideas and discoveries that stayed with us.</p><p><a href="https://studio.example.test/story-${i}">Read the full story →</a></p>`).join('')}<blockquote><p>On Monday, Jamie wrote:</p><p>Really enjoyed the last edition. Could you share the workshop dates?</p></blockquote><hr><p>You are receiving this because you subscribed to Studio North.</p><p><a href="https://studio.example.test/unsubscribe">Unsubscribe</a> · <a href="https://studio.example.test/preferences">Manage preferences</a></p></div>`;
messages.push({...messages[0],id:'newsletter',threadId:'thread-newsletter',blobId:'blob-newsletter',subject:'Studio North — Good things take shape',from:[{name:'Studio North Journal',email:'journal@studio.example.test'}],preview:'Our monthly collection of thoughtful work, practical ideas and things we have been making.',mailboxIds:{'folder-inbox':true,projects:true},keywords:{},hasAttachment:true,htmlBody:[{partId:'html',blobId:'newsletter-html',type:'text/html',size:newsletterHtml.length}],bodyValues:{text:{value:'Studio North monthly newsletter. The full edition contains eight stories.'},html:{value:newsletterHtml}},attachments:[{partId:'inline-logo',blobId:'inline-logo',name:'studio-logo.png',type:'image/png',size:68,cid:'studio-logo',isInline:true,disposition:'inline'}],headers:[{name:'Message-ID',value:'<newsletter@example.test>'},{name:'List-Unsubscribe',value:'<https://studio.example.test/unsubscribe>'}]});
const cidNewsletter=messages.find(m=>m.id==='newsletter');const cidPart=cidNewsletter.attachments[0];cidNewsletter.textBody.push({...cidPart});cidNewsletter.htmlBody.push({...cidPart});cidNewsletter.attachments=[];cidNewsletter.bodyValues['inline-logo']={value:'BINARY SENTINEL: this must never appear as prose'};
if(state==='sanitizer'){const newsletter=messages.find(m=>m.id==='newsletter');newsletter.bodyValues.html.value+='<script>document.body.dataset.fixtureUnsafe="executed"</script><meta http-equiv="refresh" content="0;url=https://127.0.0.1:5197/unsafe"><form action="https://127.0.0.1:5197/unsafe"><input value="unsafe active form"></form><img onerror="document.body.dataset.fixtureUnsafe=1" alt="handler stripped"><svg><script>unsafe</script></svg><div style="position:fixed;overflow:hidden;height:100vh;min-height:100vh">Sanitizer layout stress text</div>';}
if(state==='thread'){
 const root=messages[0];root.receivedAt=new Date(Date.now()-172800000).toISOString();root.bodyValues.text.value='Hi Alex,\n\nCan you review the project milestones before Thursday?\n\nJamie';
 messages.push({...structuredClone(root),id:'thread-middle',blobId:'blob-thread-middle',subject:'Re: Design review on Thursday',receivedAt:new Date(Date.now()-86400000).toISOString(),from:[{name:'Alex Morgan',email:'alex@example.test'}],bodyValues:{text:{value:'Hi Jamie,\n\nI have reviewed the first milestones. Can we move the accessibility review earlier?\n\nAlex'}}});
 messages.push({...structuredClone(root),id:'thread-newest',blobId:'blob-thread-newest',subject:'Re: Design review on Thursday',receivedAt:new Date(Date.now()-3600000).toISOString(),bodyValues:{text:{value:'Hi Alex,\n\nUpdated! The accessibility review is now the first milestone. The revised plan is attached for Thursday.\n\nThanks,\nJamie'}}});
}
const quotedHtml='<p>Thanks Jamie,</p><p>I have reviewed the plan and highlighted <strong>two changes</strong>.</p><ul><li>Move the milestone to Friday.</li><li>Include the accessibility review.</li></ul><p>Alex</p><blockquote><p>On Monday, Jamie wrote:</p><p>Could you review the plan?</p><blockquote><p>On Friday, Taylor wrote:</p><p>The first draft is attached.</p></blockquote></blockquote>';
const draft:any={...messages[0],id:'draft-review',from:[{email:'alex@example.test'}],to:[{email:'jamie@example.test'}],subject:'Re: Design review on Thursday',mailboxIds:{'folder-drafts':true},keywords:{$draft:true},attachments:[],bodyValues:{text:{value:'Hi Jamie,\n\nThanks for sharing. The plan looks good to me.\n\nAlex'}},...(['rich','quoted-rich'].includes(state)?{htmlBody:[{partId:'html',blobId:'html',type:'text/html',size:100}],bodyValues:{html:{value:state==='quoted-rich'?quotedHtml:'<p>Hi Jamie,</p><p>Thanks for sharing. The plan looks <strong>good</strong> to me.</p><p>Alex</p>'}}}:{})};
const domains=[{id:'domain-one',zoneId:'a'.repeat(32),name:'example.test',enabled:true,sendingVerified:true,dnsState:'verified',catchAllAccountId:accountId},{id:'domain-two',zoneId:'b'.repeat(32),name:'studio.test',enabled:true,sendingVerified:false,dnsState:'pending'}];
const entities:any={Mailbox:mailboxes,Identity:identities,Email:messages,Thread:[...new Set(messages.map(m=>m.threadId))].map(id=>({id,emailIds:messages.filter(m=>m.threadId===id).map(m=>m.id)})),Contact:[{id:'contact-jamie',name:'Jamie Chen',email:'jamie@example.test'},{id:'contact-taylor',name:'Taylor Reed',email:'taylor@example.test'}],Rule:[{id:'rule-one',name:'Project updates',isEnabled:true,sortOrder:0,condition:{from:'jamie@example.test'},actions:{addMailboxIds:['projects']}}],Domain:domains,Template:[{id:'template-one',name:'Quick follow-up',subject:'Following up',textBody:'Hi,\n\nJust checking in on this. Let me know if you need anything from me.\n\nThanks!'}],VacationResponse:[{id:'vacation',isEnabled:true,subject:'Away until Monday',textBody:'Thanks for your message. I am away this week and will reply on Monday.',fromDate:new Date().toISOString(),toDate:new Date(Date.now()+604800000).toISOString()}],EmailSubmission:['scheduled','pending','failed','uncertain','sent'].map((status,i)=>({id:`submission-${i}`,emailId:`message-${i}`,status,recoverable:status==='failed',undoStatus:i<2?'pending':'final',sendAt:new Date(Date.now()+i*3600000).toISOString(),error:status==='failed'?'The recipient address could not be reached.':null,deliveryStatus:{'jamie@example.test':{status:status==='sent'?'delivered':status==='failed'?'bounced':'queued',terminal:status==='sent'||status==='failed',updatedAt:new Date().toISOString()}}})),Migration:[],Forwarding:[]};
const workIdentities=[{id:'identity-work',name:'Alex · Morgan Studio',email:'alex@studio.example.test',verified:true,textSignature:'Alex Morgan\nMorgan Studio · Design that works',htmlSignature:'<p><strong>Alex Morgan</strong><br>Morgan Studio</p>'},{id:'identity-support',name:'Studio support',email:'hello@studio.example.test',verified:true,textSignature:'The Morgan Studio team'}];
const workMessages=messages.slice(0,4).map((m,i)=>({...structuredClone(m),id:`work-${i}`,threadId:`work-thread-${i}`,blobId:`work-blob-${i}`,subject:`Studio: ${m.subject}`,to:[{name:'Alex · Morgan Studio',email:'alex@studio.example.test'}]}));
const fixtureSettings=new Map<string,any>();
const isEmpty=state==='empty';
const fixtureDrafts=new Map<string,any>([[draft.id,draft]]);
const fixtureReceipts=new Map<string,any>();
let fixtureRevision=1;
function matchesFilter(m:any,filter:any):boolean{
 if(filter.operator){const results=(filter.conditions||[]).map((f:any)=>matchesFilter(m,f));return filter.operator==='OR'?results.some(Boolean):filter.operator==='NOT'?!results.some(Boolean):results.every(Boolean);}
 if(filter.inMailbox&&!m.mailboxIds[filter.inMailbox])return false;
 if(filter.inMailboxOtherThan&&Object.keys(m.mailboxIds).every(id=>filter.inMailboxOtherThan.includes(id)))return false;
 if(filter.hasKeyword&&!m.keywords[filter.hasKeyword])return false;if(filter.notKeyword&&m.keywords[filter.notKeyword])return false;
 if(filter.text&&!JSON.stringify(m).toLowerCase().includes(String(filter.text).toLowerCase()))return false;
 if(filter.subject&&!m.subject.toLowerCase().includes(filter.subject.toLowerCase()))return false;
 return true;
}
async function call(name:string,args:any={},id=accountId):Promise<any>{
 if(state==='loading')return new Promise(()=>{});
 if(state==='error')throw Object.assign(new Error('We couldn’t load your mail. Check your connection and try again.'),{confirmed:true});
 const [entity,method]=name.split('/');
 if(name==='Settings/get'||name==='Settings/renew')return {accountId:id,state:'fixture-1',settings:fixtureSettings.get(id)||{density:'comfortable',undoSeconds:id==='review-work'?20:10,pageSize:50,showPreview:true,confirmDelete:true,savedSearches:id==='review-work'?[{id:'search-project',name:'Project reviews',query:'subject:review'}]:[],favoriteMailboxIds:id==='review-work'?['projects']:[],forwarding:{address:'',enabled:false}},automationHealth:{status:'healthy',expiresAt:Date.now()+2592000000,renewRequired:false}};
 if(name==='Quota/get')return {accountId:id,list:[{id:'storage',used:1073741824,reserved:0,blobCount:2456,hardLimit:5368709120}]};
 if(name==='Retention/get')return {accountId:id,state:'fixture-1',trashRetentionDays:30,junkRetentionDays:30};
 if(name==='Lifecycle/get')return {accountId:id,status:'active',revision:1,purgeAfter:null};
 if(name==='Settings/set'){fixtureSettings.set(id,structuredClone(args.settings));return {accountId:id,newState:`fixture-${++fixtureRevision}`};}
 if(method==='query'){const source=[...(id==='review-work'?workMessages:messages),...fixtureDrafts.values()];const matching=isEmpty?[]:source.filter(m=>matchesFilter(m,args.filter||{}));const position=args.position||0;return {accountId:id,queryState:'fixture-1',ids:matching.slice(position,position+(args.limit||50)).map(m=>m.id),total:matching.length,position};}
 if(method==='get'){let list=isEmpty?[]:structuredClone(entities[entity]||[]);if(entity==='Domain')list=list.filter((item:any)=>id==='review-work'?item.name==='studio.test':item.name==='example.test');if(entity==='Identity'&&id==='review-work')list=structuredClone(workIdentities);if(entity==='Email'){list=[...(id==='review-work'?workMessages:list),...fixtureDrafts.values()];}if(entity==='Thread'&&id==='review-work')list=workMessages.map(m=>({id:m.threadId,emailIds:[m.id]}));if(args.ids)list=list.filter((item:any)=>args.ids.includes(item.id));return {accountId:id,state:`fixture-${fixtureRevision}`,list,notFound:[]};}
 if(method==='set'||method==='import'){
  if(args.operationId&&fixtureReceipts.has(args.operationId))return fixtureReceipts.get(args.operationId);
  const created:any={};for(const [key,value] of Object.entries(args.create||{})){
    const recordId=`${entity.toLowerCase()}-fixture-${++fixtureRevision}`,blobId=`blob-fixture-${fixtureRevision}`;
    created[key]={id:recordId,...(entity==='Email'?{blobId}: {})};
    if(entity==='Email')fixtureDrafts.set(recordId,{...draft,...structuredClone(value as any),id:recordId,blobId});
  }
  if(entity==='Email')for(const recordId of args.destroy||[])fixtureDrafts.delete(recordId);
  const receipt={accountId:id,oldState:`fixture-${fixtureRevision-1}`,newState:`fixture-${fixtureRevision}`,created,updated:Object.fromEntries(Object.keys(args.update||{}).map(k=>[k,null])),destroyed:args.destroy||[]};
  if(args.operationId)fixtureReceipts.set(args.operationId,receipt);return receipt;
 }
 return {accountId:id,state:'fixture-1',status:'verified',total:0,processed:0,hasMore:false};
}
const response=(value:any,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json'}});
const account={id:accountId,name:allAccounts[accountId]?.name||'Personal',ownerActorId:session.actorId,version:1,canManage:state!=='readonly',grants:isEmpty?[]:[{actorId:'review-jamie',actions:['mail.read','mail.draft']}]};
// Every fetch, including mutations, is intercepted locally. Never fall through to a network transport.
window.fetch=async(input:any,init:any={})=>{
 const url=new URL(typeof input==='string'?input:input.url||String(input),location.origin),path=url.pathname;
 if(url.origin!==location.origin) return response({error:'External network is disabled in this fixture.'},403);
 if(state==='loading'&&path.includes('/api/'))return new Promise(()=>{});
 if(state==='error')return response({message:'We couldn’t load this page. Check your connection and try again.'},503);
 if(path.endsWith('/jmap/session'))return response(session);
 if(path.endsWith('/jmap')){const payload=JSON.parse(init.body);const methodResponses:any[]=[];for(const [name,original,tag] of payload.methodCalls){const args={...original};for(const key of Object.keys(args).filter(key=>key.startsWith('#'))){const ref=args[key],prior=methodResponses.find(value=>value[2]===ref.resultOf&&value[0]===ref.name);let values=[prior?.[1]];let wildcard=false;for(const part of ref.path.slice(1).split('/')){if(part==='*'){wildcard=true;values=values.flatMap(value=>Array.isArray(value)?value:Object.values(value||{}));}else values=values.map(value=>value?.[part]);}args[key.slice(1)]=wildcard?values:values[0];delete args[key];}methodResponses.push([name,await call(name,args,args.accountId),tag]);}return response({methodResponses,sessionState:'fixture-1'});}
 if(path.endsWith('/api/session'))return response({user:{id:session.actorId,email:session.username,name:'Alex Morgan',displayName:'Alex Morgan',provider:'local'}});
 if(path==='/api/apps')return response({apps:[{id:'mail',name:'Mail',description:'Your mail, on your own terms.',version:'0.1.0',capabilities:[],embeds:[]}]});
 if(path.endsWith('/api/accounts'))return response({accounts:isEmpty?[]:[account,{...account,id:'review-work',name:'Studio'}]});
 if(path.includes('/api/accounts/'))return response({account,grants:account.grants,canManage:account.canManage});
 if(path.endsWith('/api/members'))return response({members:[{actorId:session.actorId,displayName:'Alex Morgan',email:'alex@example.test'},{actorId:'review-jamie',displayName:'Jamie Chen',email:'jamie@example.test'}]});
 if(path.endsWith('/api/client-info'))return response({enabled:true,sessionUrl:'https://mail.example.test/jmap/session'});
 if(path.endsWith('/api/credentials'))return response({credentials:isEmpty?[]:[{id:'credential-review',name:'My desktop mail app',accountId,actions:['mail.read','mail.organize'],expiresAt:Date.now()+2592000000,createdAt:Date.now()-86400000,revokedAt:null,version:1}]});
 if(path.endsWith('/api/domains/discovery')){const zoneId=url.searchParams.get('zoneId');const all=[...domains.map(d=>({zoneId:d.zoneId,name:d.name,status:'active'})),{zoneId:'c'.repeat(32),name:'personal.test',status:'active'},{zoneId:'d'.repeat(32),name:'workshop.test',status:'active'}];if(!zoneId)return response({domains:isEmpty?[]:all,page:1,pages:1});const index=all.findIndex(d=>d.zoneId===zoneId);return response({domain:all[index],mailExchangers:index===0?['route1.mx.cloudflare.net']:index===1?['aspmx.l.google.com']:[],existingMail:index<2,delivery:index===0?'enoughmail':index===1?'other':'none',routingCheck:'verified',providers:index===1?['Google Workspace']:[],routingDestinations:index===0?['enough-mail-ingress']:[]});}
 if(path.startsWith('/fixture-download/'))return new Response(Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII='),c=>c.charCodeAt(0)),{headers:{'Content-Type':'image/png'}});
 if(path==='/fixture-upload')return response({accountId,blobId:'local-upload',type:'application/octet-stream',size:100});
 return response({});
};
// New clients constructed by the real MailApp get the same explicit fixture transport.
MailClient.prototype.discover=async function(){this.session=session;return session;};
MailClient.prototype.call=async function(name,args,id){this.session=session;return call(name,args,id);};
const client=new MailClient();client.session=session;client.call=call;client.discover=async()=>session;client.upload=async(file:any)=>({accountId,blobId:'local-upload',type:file.type||'application/octet-stream',size:file.size});
if(screen==='Compose'){
 const key=draftCacheKey(session,accountId);localStorage.removeItem(key);
 const fields={identityId:'identity-alex',to:'jamie@example.test',cc:'',bcc:'',subject:'Re: Design review on Thursday',body:'Hi Jamie,\n\nHere are my changes to the plan.\n\nAlex',attachments:[],sendAt:'',rich:false,html:''};
 if(state==='conflict')localStorage.setItem(key,JSON.stringify({[draft.id]:{fields,emailId:draft.id,sourceEmailId:draft.id,sourceBlobId:draft.blobId,draftBaseline:{id:draft.id,blobId:draft.blobId,mailboxIds:draft.mailboxIds,keywords:draft.keywords},conflicted:true}}));
 if(state==='uncertain')localStorage.setItem(key,JSON.stringify({[draft.id]:{fields,emailId:draft.id,sourceEmailId:draft.id,sourceBlobId:draft.blobId,draftBaseline:{id:draft.id,blobId:draft.blobId,mailboxIds:draft.mailboxIds,keywords:draft.keywords},pendingSubmission:{operationId:'review-operation',args:{create:{send:{emailId:draft.id,identityId:'identity-alex'}}},fingerprint:JSON.stringify(fields)}}}));
}
if(screen==='Offline queue')localStorage.setItem(`enough-mail:offline:v1:${cacheScope(session)}:queue`,JSON.stringify(isEmpty?[]:[{id:'queued-one',accountId,expectedState:'fixture-old',args:{update:{'message-0':{'keywords/$seen':true}}}}]));
const sections=['Accounts','Domains','Identities','Mailboxes','Preferences','Contacts','Rules','Templates','Vacation reply','Delegation','Client access','Migration','Offline','Storage & retention'];
function Harness(){const [notice,setNotice]=React.useState('');const done=()=>setNotice('Fixture action completed locally.');return <><div hidden={params.get('controls')==='hidden'} className="review-controls" style={{display:params.get('controls')==='hidden'?'none':'flex',height:42,padding:'6px 12px',alignItems:'center',gap:10,background:'#e9edf4',font:'12px system-ui',borderBottom:'1px solid #ccd1dc'}}><strong>LOCAL REVIEW</strong><label>Screen <select aria-label="Review screen" value={screen} onChange={e=>location.search=`?screen=${encodeURIComponent(e.target.value)}&state=${state}&account=${accountId}`} >{['Inbox','Compose','Outbox','Offline queue',...sections].map(s=><option key={s}>{s}</option>)}</select></label><label>State <select aria-label="Review state" value={state} onChange={e=>location.search=`?screen=${encodeURIComponent(screen)}&state=${e.target.value}&account=${accountId}`}>{['populated','thread','sanitizer','empty','loading','error','readonly','onboarding','new','rich','quoted-rich','reply','replyAll','forward','conflict','uncertain'].map(s=><option key={s}>{s}</option>)}</select></label><label>Inbox <select aria-label="Review inbox" value={accountId} onChange={e=>location.search=`?screen=${encodeURIComponent(screen)}&state=${state}&account=${e.target.value}`}><option value="review-inbox">Personal</option><option value="review-work">Studio</option></select></label><span>{notice||'Fake data · All network intercepted'}</span></div><div className="mail-standalone" style={{height:params.get('controls')==='hidden'?'100dvh':'calc(100dvh - 42px)'}}>{screen==='Inbox'?<MailApp/>:<div className="mail-app" style={{display:'flex'}}>{sections.includes(screen)?<Settings key={`${screen}:${state}`} client={client} accountId={accountId} initialSection={screen as any} onClose={done}/>:screen==='Compose'?<Compose client={client} accountId={accountId} identities={state==='empty'?[]:accountId==='review-work'?workIdentities:identities} mailboxes={mailboxes} draft={['populated','rich','quoted-rich','conflict','uncertain'].includes(state)?draft:undefined} reply={['reply','replyAll','forward'].includes(state)?messages[0]:undefined} mode={state as any} onClose={done} onSaved={()=>{}} onSubmitted={done}/>:screen==='Outbox'?<Outbox client={client} accountId={accountId} onClose={done} onEdit={done}/>:<OfflineQueue client={client} session={session} onClose={done} onChanged={done}/>}</div>}</div></>}
createRoot(document.getElementById('root')!).render(<Harness/>);
